# Generated by Django 3.2.5 on 2022-07-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20220630_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='conclude',
            field=models.TextField(blank=True, verbose_name='まとめ'),
        ),
    ]
