# Generated by Django 3.2.5 on 2022-07-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20220704_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='user_message',
            field=models.TextField(blank=True, null=True, verbose_name='ユーザメッセージ'),
        ),
        migrations.AddField(
            model_name='diary',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='ユーザアイコン'),
        ),
    ]
